server:
  port: 8081

spring:
  application:
    name: Bootstrap Spring Boot

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${DATABASE_NAME:curses}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true                          # optional, helpful for debug
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # explicit is better

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}         # make it env-configurable too
      port: 27017
      database: books

# spring.kafka.bootstrap-servers specifies the address of your Kafka broker, and spring.kafka.consumer.group-id specifies the consumer group ID for your application
spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}
  consumer:
    group-id: ${KAFKA_GROUP_ID:my-group-id}
