package org.example.Controller;

import java.util.Optional;
import org.example.Repository.UserRepository;
import org.example.models.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/db") // This means URL's start with /demo (after Application path)
public class DbController {

  private final UserRepository userRepository;

  /**
   * This means to get the bean called userRepository Which is auto-generated by Spring, we will use
   * it to handle the data
   */
  @Autowired
  public DbController(UserRepository userRepository) {
    this.userRepository = userRepository;
  }

  @PostMapping(path = "/add") // Map ONLY POST Requests
  public ResponseEntity<User> addNewUser(
      @RequestBody User user
  ) {
    userRepository.save(user);
    return ResponseEntity.ok(user);
  }

  @GetMapping(path = "/get/{userId}")
  public User getUser(@RequestParam Long userId) {
    Optional<User> user = userRepository.findById(userId);
    return user.orElse(null);
  }
}
